import Head from 'next/head'
import { Heading, Flex } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Michała</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex height="100vh" alignItems="center" justifyContent="center">
          <Heading>Install Chakra UI In NextJS 13</Heading>
        </Flex>
      </main>
    </>
  )
}
